version: "3.9"
services:

    Nginx:
        container_name: Nginx
        image: nginx:stable
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - /d/Docker/Nginx/etc:/etc/nginx
            - /d/Docker/Nginx/html:/usr/share/nginx/html
            - /d/Docker/Nginx/log:/var/log/nginx
        networks:
            default:
                ipv4_address: 172.18.1.10

    SSV2:
        container_name: SSV2
        image: ghcr.io/shadowsocks/ssserver-rust:latest
        restart: always
        ports:
            - 19899:19899/tcp
            - 19899:19899/udp
        volumes:
            - /d/Docker/SSV2/v2ray-plugin:/etc/shadowsocks-rust/v2ray-plugin
            - /d/Docker/SSV2/config.json:/etc/shadowsocks-rust/config.json
            - /d/Docker/SSV2/nord.im.key:/etc/shadowsocks-rust/nord.im.key
            - /d/Docker/SSV2/nord.im.pem:/etc/shadowsocks-rust/nord.im.pem
        depends_on:
            - Nginx
        # sslocal -b "127.0.0.1:1080" -s "127.0.0.1" -m "aes-256-gcm" -k "Jaydar@123." --plugin "v2ray-plugin" --plugin-opts "server;mode=websocket;host=127.0.0.1;pah=/ws"
networks:
    default:
        # external: true
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.1.0/24